version: '3.3'

services:
   db:
     image: mariadb
     volumes:
       - db_data:/var/lib/mysql
       - ./bin/dbcheck.sh:/usr/local/bin/dbcheck.sh
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     image: wordpress:latest
     volumes:
       - ./bin/install-cli.sh:/usr/local/bin/install-cli.sh
       - ./bin/install-wp.sh:/usr/local/bin/install-wp.sh
       - ./wp-content:/var/www/html/wp-content
       - ./plugin-project:/var/www/html/wp-content/plugins/plugin-project
       - ./theme-project:/var/www/html/wp-content/themes/theme-project
     depends_on:
       - db
     ports:
       - "13000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
    db_data: {}
